### ISSUE TITLE
Specifying existing file(s) as attachments

### ISSUE THREAD

**Issue by Silverbug** [SalesforceLabs/FlowEmailComposer#4]
Is there a way to specify (prepopulate) attachments as part of the flow? (without the user having to manually upload the file)

We want to be able to create a screen flow that lets users send an email to a contact with a file that already exists on the object (ie pdf file on the quote)

**Comment by surendranune** [comment]
The component currently pre-populates only the attachments associated with email templates. But the component is flexible enough to customise it according to your own needs.
