### ISSUE TITLE
Visualforce Template Attachments

### ISSUE THREAD

**Issue by sholombc** [SalesforceLabs/FlowEmailComposer#5]
When I try sending an email with a Visualforce Template with an attachment in the template I get this error:

`Something went wrong: SendEmail failed. First exception on row 0; first error: INVALID_ID_FIELD, The ID provided is not of types ContentVersion or Document.: [entityAttachments, null]`

When I do something like this

` <messaging:attachment filename="sample.pdf" renderAs="PDF">
			<apex:repeat var="cx" value="{!relatedTo.Cases}">
				Case Number: {!cx.CaseNumber}
				Origin: {!cx.Origin}
				Creator Email: {!cx.Contact.email}
				Case Number: {!cx.Status}
			</apex:repeat> 
		</messaging:attachment>`

**Comment by surendranune** [comment]
only classic email templates are supported.
